### ISSUE TITLE
Missed segmentations in laser plugin

### ISSUE THREAD

**Issue by whoutman** [tue-robotics/ed_sensor_integration#15]
src/laser/plugin.cpp:
When an object is partially detected around the minimum angle of the laser, no object is segmented.

**Comment by whoutman** [comment]
See https://github.com/tue-ropod/ropod-project-software/commit/a9472e9e7d7e47871d5a14e8f1436d31f7865bfd

**Comment by MatthijsBurgh** [comment]
You are welcome to create a pull request.

**Comment by MatthijsBurgh** [comment]
@whoutman Did it solve the problem? Is this the version you use right now?
